name: Device Blobs Extraction

on:
  workflow_dispatch:
    inputs:
      DEVICE_BRANCH:
        description: "Device tree's branch"
        required: true
      VENDOR_BRANCH:
        description: "Vendor tree's branch"
        required: true
      STARTING_HASH:
        description: 'Commit hash to start processing from (optional)'
        required: false
      SIGN_COMMITS:
        description: 'Enable GPG signing for commits'
        default: 'true'
        required: false

jobs:
  Extract-Sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Clean up the environment
        uses: rokibhasansagar/slimhub_actions@main

      - name: Cleanup Workspace
        run: rm -rf ${{ github.workspace }}/*

      - name: Set-up main directory with stripped clang and jdk21
        run: |
          git clone --depth 1 --single-branch -b main https://gitlab.com/dogpoopy/blobs_extractor.git .
          rm -rf .git

      - name: Set up Git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      
      - name: Set up SSH Key for GPG Signing (Optional)
        if: ${{ inputs.SIGN_COMMITS == 'true' }}
        run: |
          mkdir -p .ssh
          echo "${{ secrets.SSH_PUBKEY }}" > .ssh/key.pub
          echo "${{ secrets.SSH_PRIVKEY }}" > .ssh/key
          chmod 400 .ssh/key.pub
          chmod 400 .ssh/key
          git config --global user.signingkey "${{ github.workspace }}/.ssh/key.pub"
          git config --global gpg.format ssh
          git config --global commit.gpgsign true

      - name: Clone Device, Vendor, Dump and Extract Tools
        run: |
          git clone --depth=1 -b lineage-22.1 https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools
          git clone --depth=1 -b lineage-22.1 https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
          git clone https://github.com/Fake-suns/android_device_xiaomi_miuicamera-chenfeng.git -b ${{ github.event.inputs.DEVICE_BRANCH }} device/xiaomi/miuicamera-chenfeng
          git clone https://codeberg.org/cyberDay777/miuicam.git -b ${{ github.event.inputs.VENDOR_BRANCH }} vendor/xiaomi/miuicamera-chenfeng
          git clone --depth 1 --single-branch -b missi-user-15-AQ3A.240912.001-OS2.0.2.0.VNJINXM-release-keys https://dumps.tadiphone.dev/dumps/xiaomi/chenfeng.git dump

      - name: Set Commit Range Starting from User-Specified Commit
        id: set_commit_range
        run: |
          cd device/xiaomi/miuicamera-chenfeng
          if [ -n "${{ github.event.inputs.STARTING_HASH }}" ]; then
            commit_range="${{ github.event.inputs.STARTING_HASH }}..HEAD"
          else
            commit_range="HEAD"
          fi
          echo "commit_range=$commit_range" >> $GITHUB_ENV

      - name: Process and Commit Changes
        run: |
          export PYTHONPATH=${{ github.workspace }}/tools/extract-utils:$PYTHONPATH

          process_commit() {
            commit_hash=$1
            python3 extract-files.py ${{ github.workspace }}/dump
            python3 extract-files.py -m
            cd ${{ github.workspace }}/vendor/xiaomi/miuicamera-chenfeng
            if [ -n "$(git status --porcelain)" ]; then
              commit_message=$(cd ${{ github.workspace }}/device/xiaomi/miuicamera-chenfeng && git log -1 --format=%B $commit_hash)
              commit_author=$(cd ${{ github.workspace }}/device/xiaomi/miuicamera-chenfeng && git log -1 --format="%an <%ae>" $commit_hash)
              commit_date=$(cd ${{ github.workspace }}/device/xiaomi/miuicamera-chenfeng && git log -1 --format=%ci $commit_hash)
              export GIT_COMMITTER_DATE="$commit_date"
              git add .
              git commit -m "$commit_message" --author="$commit_author"
            fi
            cd ${{ github.workspace }}/device/xiaomi/miuicamera-chenfeng
          }

          cd ${{ github.workspace }}/device/xiaomi/miuicamera-chenfeng
          for commit in $(git rev-list --reverse ${{ env.commit_range }}); do
            if git show --name-only $commit | grep -qE 'extract-files.py|proprietary-files.txt'; then
              git checkout $commit
              process_commit $commit
            fi
          done

      - name: Push Vendor Changes
        run: |
          cd vendor/xiaomi/miuicamera-chenfeng
          git push -f "https://x-access-token:${{ secrets.PAT }}@codeberg.org/cyberDay777/miuicam.git" ${{ github.event.inputs.VENDOR_BRANCH }}
