name: Device Blobs Extraction

on:
  workflow_dispatch:
    inputs:
      DEVICE_BRANCH:
        description: "Device tree's branch"
        required: true
      VENDOR_BRANCH:
        description: "Vendor tree's branch"
        required: true
      STARTING_HASH:
        description: 'Commit hash to start processing from (optional)'
        required: false

jobs:
  Extract-Sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Cleanup Workspace
        run: rm -rf ${{ github.workspace }}/*

      - name: Set up Git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Clone stripped clang and jdk21
        run: |
          git clone https://gitlab.com/dogpoopy/blobs_extractor.git .
          rm -rf .git

      - name: Clone Extraction Utilities
        run: |
          git clone --depth=1 -b lineage-22.0 https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools
          git clone --depth=1 -b lineage-22.0 https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils

      - name: Clone Device, Vendor, and Dump
        run: |
          git clone https://github.com/aosp-realm/android_device_xiaomi_apollo -b ${{ github.event.inputs.DEVICE_BRANCH }} device/xiaomi/apollo
          git clone https://github.com/aosp-realm/android_vendor_xiaomi_apollo -b ${{ github.event.inputs.VENDOR_BRANCH }} vendor/xiaomi/apollo
          git clone --depth 1 --single-branch https://gitlab.com/dogpoopy/apollo_dump_V14.0.4.0.SJDMIXM.git dump

      - name: Set Commit Range Starting from User-Specified Commit
        id: set_commit_range
        run: |
          cd device/xiaomi/apollo
          
          if [ -n "${{ github.event.inputs.STARTING_HASH }}" ]; then
            commit_range="${{ github.event.inputs.STARTING_HASH }}..HEAD"
          else
            commit_range="HEAD"
          fi

          echo "commit_range=$commit_range" >> $GITHUB_ENV

      - name: Fetch Commits in Device Tree
        run: |
          cd device/xiaomi/apollo
          git fetch --all

      - name: Process Commits in Device Tree
        run: |
          cd device/xiaomi/apollo
          
          for commit in $(git rev-list --reverse ${{ env.commit_range }}); do
            if git show --name-only --oneline $commit | grep -E 'extract-files.sh|setup-makefiles.sh|proprietary-files.txt'; then
              bash extract-files.sh ${{ github.workspace }}/dump
              cd ../../../vendor/xiaomi/apollo
              git fetch https://github.com/aosp-realm/android_device_xiaomi_apollo $commit
              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit --reuse-message="$commit" --author="$(git show -s --format='%an <%ae>' $commit)"
              else
                echo "No changes in vendor directory, skipping commit."
              fi
              cd -
            fi
          done

      - name: Push Vendor Changes
        run: |
          cd vendor/xiaomi/apollo
          git push origin ${{ github.event.inputs.VENDOR_BRANCH }}
